apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dep-devsecops
  name: dep-devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dep-devsecops
  template:
    metadata:
      labels:
        app: dep-devsecops
    spec:
      containers:
      - image: docker.io/phanikumart/devsecops:latest
        name: devsecops
        ports:
          - containerPort: 80
        